### ISSUE TITLE
🛠️ [TASK] : Cardano Blockchain integration API: Hermes Implementation (Rust Module)

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/hermes#106]
## Subtasks

- [x] #174

**Comment by FelipeRosa** [comment]
https://github.com/input-output-hk/hermes/issues/171 is needed in order to create chain update events.

**Comment by FelipeRosa** [comment]
Blocked by: https://github.com/input-output-hk/hermes/issues/180
