### ISSUE TITLE
🛠️ [TASK] : WASM `Module` benchmark

### ISSUE THREAD

**Issue by Mr-Leshiy** [input-output-hk/hermes#79]
### Summary

Implement a benchmark for the `Module::call_func` function.

### Description

Write a benchmark for [`Module::call_func`](https://github.com/input-output-hk/hermes/blob/170207ff72c1146e02d6e6c307062fb4f6db439c/hermes/bin/src/wasm/module.rs#L78) to measure how long it takes to call a wasm function taking into account that during each execution a clean wasm state is initialised (which could be costly).

**Comment by stevenj** [comment]
Make sure we benchmark this with the wasi bindings PR merged, as it will be a better indication of the overhead in creating wasm instances.
